-- -- goher.nvim
-- return {
--   {
--     "olexsmir/gopher.nvim",
--     ft = "go",
--     -- branch = "develop"
--     build = function()
--       vim.cmd.GoInstallDeps()
--     end,
--     ---@module "gopher"
--     ---@type gopher.Config
--     opts = {},
--   },
-- }
